version: "4.0"

services:
  database:
    image: postgres:13
    container_name: tech_challenge_ecommerce
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  tech-challenge-ecommerce-auth-api:
    build:
      context: ./tech.challenge.ecommerce.auth.api
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - DB_SERVER=database
      - SERVER_PORT=8080
    ports:
      - "8080:8080"

  tech-challenge-ecommerce-items-api:
    build:
      context: ./tech.challenge.ecommerce.items.api
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - DB_SERVER=database
      - AUTH_PORT=8080
      - SERVER_PORT=8081
    ports:
      - "8081:8081"

  tech-challenge-ecommerce-bag-api:
    build:
      context: ./tech.challenge.ecommerce.bag.api
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - DB_SERVER=database
      - AUTH_PORT=8080
      - SERVER_PORT=8082
    ports:
      - "8082:8082"

  tech-challenge-ecommerce-payment-api:
    build:
      context: ./tech.challenge.ecommerce.payment.api
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - DB_SERVER=database
      - AUTH_PORT=8080
      - SERVER_PORT=8083
    ports:
      - "8083:8083"