spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl: none
      show-sql: true
  sql:
    init:
      platform: postgresql
  datasource:
    url: jdbc:postgresql://${DB_SERVER:localhost}:${DB_PORT:5432}/${POSTGRES_DB:postgres}?stringtype=unspecified
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
    driverClassName: org.postgresql.Driver
    connectionTimeout: 30000
    jpaTransactionManagerTimeout: 120
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
jwt:
  token: ${JWT_TOKEN:cc2b2030-6fc5-4b1e-a2b5-57a3cde1e2c0}

server:
  port: ${PORT:8080}